name: Publish VS Code Extension
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run compile
      - uses: actions/setup-git@v3
        with:
          name: tudoraneau
          email: tudoraneau@gmail.com
      - run: npm install -g @vscode/vsce
      - run: vsce publish --pat ${{ secrets.VSCE_PAT }}
